#!/usr/bin/env python3
"""Generate compile-time C include table from nethack_strings_merged.json.

Output format:
    { "key", "value" },

Key mapping:
- <hash>:en:<i> -> entry.zh[i]
- <hash>:arg:<idx>:<j> -> entry.args[*].zh[j] where args[*].idx == idx
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def c_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def add_if_nonempty(rows: dict[str, str], key: str, value: Any) -> None:
    if not isinstance(value, str):
        return
    if not value:
        return
    rows[key] = value


def build_rows(data: dict[str, Any]) -> list[tuple[str, str]]:
    by_key: dict[str, str] = {}

    for section in data.values():
        if not isinstance(section, dict):
            continue

        for digest, entry in section.items():
            if not isinstance(entry, dict):
                continue

            zh_list = entry.get("zh")
            if isinstance(zh_list, list):
                for i, txt in enumerate(zh_list):
                    add_if_nonempty(by_key, f"{digest}:en:{i}", txt)

            args = entry.get("args")
            if isinstance(args, list):
                for arg in args:
                    if not isinstance(arg, dict):
                        continue
                    idx = arg.get("idx")
                    zh_arg = arg.get("zh")
                    if not isinstance(idx, int) or not isinstance(zh_arg, list):
                        continue
                    for j, txt in enumerate(zh_arg):
                        add_if_nonempty(by_key, f"{digest}:arg:{idx}:{j}", txt)

    return sorted(by_key.items(), key=lambda kv: c_escape(kv[0]))


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate tr_table_data.inc from nethack_strings_merged.json")
    parser.add_argument(
        "-i",
        "--input",
        default="nethack_strings_translated_export.json",
        help="Input merged json path",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="mods/zh_translate/tr_table_data.inc",
        help="Output C include path",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)

    data = json.loads(in_path.read_text(encoding="utf-8"))
    rows = build_rows(data)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by generate_tr_table_inc.py. Do not edit manually. */\n")
        for k, v in rows:
            f.write(f'{{ "{c_escape(k)}", "{c_escape(v)}" }},\n')

    print(f"wrote {len(rows)} entries to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
